version: '3.9'

services:
  mysql:
    build: ./mysql
    image: mysql
    container_name: mysql_container
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  app:
    build: ./app
    image: app
    networks:
      - db_network
      - site_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: testdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - "5423:824"
    networks:
      - site_network
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_volume:

networks:
  db_network:
  site_network: